### ISSUE TITLE
能不能添加一个简单的使用说明呢？

### ISSUE THREAD

**Issue by asd2003asd** [CNMan/dnscrypt-proxy-config#1]
使用你的配置国内有些网站打不开，比如京东，hao123等等。

**Comment by CNMan** [comment]
`dnscrypt-forwarding-rules.txt` 中的 `114.114.114.114,223.5.5.5,119.29.29.29` 换成你运营商当地的DNS看看

**Comment by asd2003asd** [comment]
好的，感谢回复，我已经知道原因了，是被这个dnscrypt-blacklist-domains.txt广告规则屏蔽了。
