### ISSUE TITLE
不能设置本地DNS为127.0.0.1

### ISSUE THREAD

**Issue by lijian8** [CNMan/dnscrypt-proxy-config#10]
首先，非常感谢，现在的配置文件很好用。
只是有一个遗憾的小问题，按照现有的配置，可以在本机或者其它机器上，通过真实的IP地址，获得正常的DNS解析；但是通过127.0.0.1，就无法返回DNS解析，提示是dns timed out
比如，本机地址为192.168.1.10，通过nslookup example.com 192.168.1.10， 可以正常的返回DNS解析。而通过nslookup example.com 127.0.0.1，就无法正常解析。
查看查询的Log文件，里面的信息是，
127.0.0.1	example.com	A	PASS
127.0.0.1	example.com	AAAA	SYNTH
127.0.0.1	example.com	A	PASS
127.0.0.1	example.com	AAAA	SYNTH

不知这是什么问题？在几台不同的windows机器上使用，都有同样的问题，dnscrypt-proxy的版本是最新的2.0.19

**Comment by CNMan** [comment]
不知道哪里出问题了，监听0.0.0.0按道理讲本机127.0.0.1应该也能解析。

参考这个改监听IP试试
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L36

**Comment by lijian8** [comment]
感谢回复。监听IP改成127.0.0.1:53，也还是不行。这真的是太奇怪了。

**Comment by CNMan** [comment]
```cmd
netstat -nao | findstr "127.0.0.1:53"  //最后一列是进程PID
tasklist | findstr 进程PID
```
看看是不是53被其它程序占用了

**Comment by lijian8** [comment]
嗯，查过了，就是dnscrypt-proxy占着这个端口。用真实IP，是可以返回正确的结果，就是不能用127.0.0.1

**Comment by CNMan** [comment]
那我就不知道是什么原因了，你再排查吧

**Comment by lijian8** [comment]
好的，谢谢了。
