### ISSUE TITLE
Cloaking应当被删除

### ISSUE THREAD

**Issue by Sraw** [CNMan/dnscrypt-proxy-config#13]
首先上游指向国外安全的加密DNS，Cloaking作为防止DNS污染是完全没有意义的。
其次不知道是hosts和dnscrypt对于域名匹配的实现有区别，还是Cloaking的源本身就有问题。除了规则中有的以外，所有匹配*.github.com的域名都会被解析到github.com上。这导致非常多的github相关服务不能使用，譬如api.github.com以及developer.github.com。
同样的情况也发生在google.com上。

因此我建议完全删除Cloaking Rules。或者仅保留localhost作为/etc/hosts文件的代替品，以供临时修改dns。

**Comment by CNMan** [comment]
一年前就已经默认禁用了 #6
