### ISSUE TITLE
配置文件导致大批Google域名dns解析失败

### ISSUE THREAD

**Issue by zigzaghumor** [CNMan/dnscrypt-proxy-config#17]
包括gstatic，谷歌翻译，Google usercontent 等

**Comment by CNMan** [comment]
默认禁用域名黑名单 https://github.com/CNMan/dnscrypt-proxy-config/commit/a9b47733f40da98279a87949d0ec2c4824af66c3

**Comment by cljnnn** [comment]
可以将误封的域名加入到 dnscrypt-whitelist-domains.txt
