### ISSUE TITLE
怎么添加到invizible

### ISSUE THREAD

**Issue by biange200** [CNMan/dnscrypt-proxy-config#18]
你好 我手机上用的是invizible
你的文件怎么添加到invizible  哪些可以添加 怎么弄
![Screenshot_2022-01-25-16-59-38-48_7016ae331e6b0e204f345bba08185605.jpg](https://user-images.githubusercontent.com/37582806/150945284-4dfd6232-93e3-482f-bcde-6f36a43ae1db.jpg)
![Screenshot_2022-01-25-16-59-53-78_7016ae331e6b0e204f345bba08185605.jpg](https://user-images.githubusercontent.com/37582806/150945322-5ddd6916-5dab-43ab-8937-d30a5466d35f.jpg)
 有没有114的DNS 怎么弄可以添加到invizible的dnscrypt服务器

**Comment by CNMan** [comment]
去invizible提问
