### ISSUE TITLE
alidns和dnspod用不了

### ISSUE THREAD

**Issue by biange200** [CNMan/dnscrypt-proxy-config#19]
![Screenshot_2022-01-25-17-34-29-57_7016ae331e6b0e204f345bba08185605.jpg](https://user-images.githubusercontent.com/37582806/150951274-4daf7761-fa4a-4c76-b869-189672f4f74f.jpg)

中国大陆的阿里腾讯dns怎么用不了

**Comment by CNMan** [comment]
能用的DNS列表在 https://github.com/DNSCrypt/dnscrypt-resolvers
不是随便拿个DNS就能用
