### ISSUE TITLE
不能访问国内网站？

### ISSUE THREAD

**Issue by ghost** [CNMan/dnscrypt-proxy-config#5]
看日志dnscrypt-proxy是运行的，本地DNS设置为127.0.0.1，但不能访问国内网站，根据“dnscrypt-forwarding-rules.txt 中的 114.114.114.114,223.5.5.5,119.29.29.29 换成你运营商当地的 DNS 看看”这条操作也不行？？
不好意思，我太笨了。

**Comment by CNMan** [comment]
具体是哪个网站？你这样问我也是一头雾水
可能你需要把所有`.log`文件都传上来看看

**Comment by m1w22** [comment]
我至今都不明白，黑名单域名为什么会有163.com?

**Comment by CNMan** [comment]
@mrw79 看了一下，确实需要排除`163.com`主域名，已反馈给上游 https://github.com/missdeer/blocklist/issues/18 ，修正之前你可以把 `163.com` 放入 `dnscrypt-whitelist.txt`

**Comment by littlekign** [comment]
i'm using the dnscrypt-proxy on openwrt, i can't access to google ,youtube,facebook,etc.what's wrong with the resolver csico? should i change the server?

**Comment by CNMan** [comment]
@littlekign 
哪种情况？
1、解析结果正确（国内本来就不能直连上，需要重新启用[cloaking rules](https://github.com/CNMan/dnscrypt-proxy-config/commit/24964ae23ccf3c874a01e0eb7480268b3c695f5c)或使用代理）
2、解析结果错误或不能解析（需要看log确定问题所在）
