### ISSUE TITLE
打开github样式加载不出来

### ISSUE THREAD

**Issue by mcnk328** [CNMan/dnscrypt-proxy-config#6]
![2.png](https://i.loli.net/2018/06/30/5b378e0505223.png)
![1.png](https://i.loli.net/2018/06/30/5b378e0521e3d.png)

**Comment by mcnk328** [comment]
发现使用了“dnscrypt-cloaking-rules.txt”，会导致样式加载不出来，注释掉就好了

**Comment by CNMan** [comment]
那可能是上游项目（ https://github.com/googlehosts/hosts ）的数据有问题，我默认禁用了吧
