### ISSUE TITLE
为什么您的配置文件没有 server_names 这一项

### ISSUE THREAD

**Issue by ghost** [CNMan/dnscrypt-proxy-config#8]
dns over https 需要用到 server_names 吗

**Comment by CNMan** [comment]
官方默认配置也是注释掉的
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L30

怎么用麻烦去看官方文档 https://dnscrypt.info/doc
